version: '1'
services:
    web:
        container_name: travello
        restart: always
        build:
            context: .
            dockerfile: ./.docker/Dockerfile_dev
        image: travello
        command: angular-http-server -p 4200
        ports:
            - 4200:4200
